### ISSUE TITLE
BCLib incompatible

### ISSUE THREAD

**Issue by Interstellar-Cow** [paulevsGitch/BCLib#114]
[crash-2022-03-08_16.12.51-client.txt](https://github.com/paulevsGitch/BCLib/files/8209715/crash-2022-03-08_16.12.51-client.txt)

**Comment by paulevsGitch** [comment]
Looks like you are using wrong version of other mods due to:
- java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
- java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
- Redirector iris$redirectLogSpam(Lorg/slf4j/Logger;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V in mixins.iris.json:MixinShaderInstance from mod iris failed injection check, (0/1) succeeded. Scanned 1 target(s)

I don't see any bugs related to BCLib
