### ISSUE TITLE
Crash on using anvil

### ISSUE THREAD

**Issue by Lozf** [paulevsGitch/BCLib#116]
Whenever I try to use the anvil it crashes.  Here's my crash report, I'm using fabric 1.18.2, and bclib 1.4.0 
I just tried with only better nether, bclib, and fabric API.

 https://gist.github.com/Lozf/e9e302ad765f90d629f70145d03917d9

**Comment by Kuggle01** [comment]
I had the same problem, now I know it wasn't my modpack since you've tested it with just BClib, fabric, and better nether

**Comment by Lozf** [comment]
Also, I just tested with the Minecraft anvil and then the better nether anvil- both of them caused a crash.

**Comment by McGodMan** [comment]
I have a similar crash, only my game crashes when I use the GUI rather than just opening it.

https://gist.github.com/McGodMan/f21fe7eb00831ac5ee3211df74fac2c9

Game crashes when doing 1 of 3 things; 
 - Shift-clicking item into first slot on anvil
 - Manually moving item into first slot on anvil
 - Manually moving item into second slot on anvil

I am using a lot of mods and I have no idea which one is preventing the initial crash (if any) but the list should be in the log.

As another note, I tried with just bclib and fabric api and got the same result as Lozf did.
Hopefully the extra detail helps in solving the issue.

**Comment by paulevsGitch** [comment]
Issue source is already known - Mojang registry freeze feature in 1.18.2

**Comment by McGodMan** [comment]
That's good to know, on another note I found which mod was letting me into the GUI;

The crash log: https://gist.github.com/McGodMan/9a934be1d6024120bddc79bc5cf33a86

The mod: https://github.com/RelativityMC/C2ME-fabric/releases/tag/0.2.0%2Balpha.7

Not sure if this helps any but good luck either way.

**Comment by SpigotDE** [comment]
Same here with the mod "On a stick" when right clicking a anvil stick

https://github.com/andantet/onastick/issues/6

**Comment by quiqueck** [comment]
Please have a look at our 1.4.1 release and check if it fixes the issue for you.

**Comment by SpigotDE** [comment]
BCLib 1.4.1 fixed the issue , much love <3

**Comment by SpigotDE** [comment]
btw anvil on stick works too

**Comment by McGodMan** [comment]
Solved on my end too, even with the mod letting me into the GUI added

**Comment by quiqueck** [comment]
Thanks for your quick feedback. I'll close the issue for now.
