### ISSUE TITLE
[Compatibility][Enhancement] Change vanilla alpha glow shaders to Fabric Rendering

### ISSUE THREAD

**Issue by coderbot16** [paulevsGitch/BCLib#12]
The implementation relies on modified vanilla core shaders, which is essentially the least-compatible way of going about things. The Fabric Rendering API provides a standard way of creating emissive textures: https://github.com/FabricMC/fabric/blob/dfdb52d6e50f6ac62ca9cae6397529f80052617f/fabric-renderer-api-v1/src/main/java/net/fabricmc/fabric/api/renderer/v1/material/MaterialFinder.java#L106

That being said, I've heard that [CTM-F](https://github.com/PepperCode1/ConnectedTexturesMod-Fabric) might have support for emissive overlays defined in resource packs, though it isn't quite as convenient as the `_e` system.

**Comment by paulevsGitch** [comment]
**Tests:**

**Vanilla**
(Everything works)

![2021-07-19_02 18 49](https://user-images.githubusercontent.com/17707380/126085181-b89e3125-74c9-4f88-848e-abbb1ea2584e.png)

**Sodium**
(Item & Entities work, block don't)

![2021-07-19_02 16 41](https://user-images.githubusercontent.com/17707380/126085208-4359f8a3-ea24-49e6-a67d-600e4c3574b6.png)

**Iris [Without shaders]**
(Everything works)

![2021-07-19_02 20 17](https://user-images.githubusercontent.com/17707380/126085220-31f9d70a-8a31-485f-a7ba-2b866ce26560.png)

**Iris [With shaders - Complementary]**
(Nothing works - missing emissive shader textures support)

![2021-07-19_02 20 09](https://user-images.githubusercontent.com/17707380/126085237-802a9de7-9cfc-4060-80ab-d55b8d081f99.png)

**Canvas**
(Nothing works, wrong Sky rendering, some built-in shaders support)

![2021-07-19_02 26 37](https://user-images.githubusercontent.com/17707380/126085329-e233955c-aa92-472c-a9ae-e72d83249a29.png)

**Optifine [With Optifabric, Without shaders]**
(Blocks works - same emissive texture suffix, entities don't)

![2021-07-19_02 31 07](https://user-images.githubusercontent.com/17707380/126085447-fed4294b-285f-42c4-aa9c-7ea7ae221f0b.png)

**Optifine [With Optifabric, With shaders - Complementary]**
(Everything works)

![2021-07-19_02 32 36](https://user-images.githubusercontent.com/17707380/126085483-df9f9165-ed83-419e-8228-a7000d6b80af.png)

**Resuts**
- Vanilla +
- Sodium +/-
- Iris +/-
- Canvas -
- Optifine +

**Conclusion:**
The method is not completely incompatible - it is halfly compatible. If mod uses same emissive format or have built-in support for vanilla shaders everything works fine and the worst-case scenario is just missing emission (without game crash or other conflicts). I think it is possible to enhance system and add support for Fabric render layers (this will probably be the best solution, but it will require some research)

**Comment by coderbot16** [comment]
OptiFine has its own system for emissive textures based on `_e` suffixes that works by adding fullbright quads to baked models, so I'm not sure if your system is actually active there as you say.

The best solution, IMO, is using the Fabric Rendering API to add fullbright overlay quads to models. FRAPI would even work with Sodium if users have Indium installed. It's a lot less likely that things will fully work when you start trying to define custom render layers for terrain or use custom shader programs.

**Comment by paulevsGitch** [comment]
> OptiFine has its own system for emissive textures based on _e suffixes that works by adding fullbright quads to baked models, so I'm not sure if your system is actually active there as you say.

It is actually not working, but it uses the same suffix system, and when Optifine loads all materials - they will be added into Optifine rendering system automatically and will work with same behavior as in vanilla

**Comment by paulevsGitch** [comment]
I tried several times to re-make this feature to work with Fabric emissive materials or alter AO calculations, but all these ways seems to be no working and sometimes incompatible with other mods. So, instead of using Fabric rendering API I decided to use vanilla shaders, but I changed system a bit:
- Alpha Emission is now fixed value - 254, no more and no less, so there will be no problems with mipped textures and mostly "bad made" textures.
- Shaders were fixed to run on all OS and were optimized a bit
- If there is a Canvas installed there is a small code part that will add Canvas shaders for same blocks with emission (only if there is no shader for this block)

As a bonus now BCLib + Canvas can be used to enable emissive textures from resourcepacks

![2021-08-01_14 35 35](https://user-images.githubusercontent.com/17707380/127770081-8aa97f26-7818-4ca3-bbdd-0cf2311c89e8.png)

There are also other benefits to keep this system:
- Easy to override and manage shaders - with simple resourcepacks
- Easy disabling/enabling this shaders - also with resourcepacks
- Compatibility with already existing emissive patterns (Optifine) and now with canvas
- No obvious incompatibilities with other mods like Sodium - emissive materials will just work as normal blocks (by incompatibilities I mean crashes, bugs and impossibility for player to launch both mods together)
- Vanilla friendly - this will work on all systems as Mojang designed shaders to work like this

**Comment by paulevsGitch** [comment]
So, this system will stay as it is (updated since 0.3.0), other mods that are not compatible with it (mostly sodium) already have their own rendering pipelines, and make system compatible with each rendering mod is probably impossible. In this case the best criteria of compatibility - stable working modpack, and this system will work stable. If, for example, Iris will implement its own emissive textures I will make the same thing as with optifine - disable atlas modification and skip all texture & model operations
