### ISSUE TITLE
BaseOreBlock and other LootProviders break other mods expectations

### ISSUE THREAD

**Issue by lukebemish** [paulevsGitch/BCLib#143]
Mods may have an expectation, in vanilla and beyond, that getting a loot table for a block will get those items that would be dropped from it. Several types of blocks provided by BCLib break this expectation needlessly - that is, without offering any functionality that could not be provided through a loot table. I have fixed this on my end where it came up - see lukebemish/excavated_variants#46 - but I thought I should make you aware that this can lead to mod compat issues. It could be fixed by using the new datagen system in fabric to generate loot tables instead, or even by using something like ARRP.

**Comment by paulevsGitch** [comment]
BClib, BN, BE and Eden blocks use internal loot overrides instead of json loot tables. Reason is simple - hundreds of blocks will require hundreds of jsons, which potentially will require updates with MC during version changes, will be almost identical and will increase jar size more than actual (wich is important for mods with huge amount of assets). Loot table replacement existed since 1.16.5 and didn't cause any problems before. LootProvider interface was introduced in the newest version as a replacement for many internal overrides existed before (which should reduce code amount, suggestion #78) - instead of overriding getDrops block will use getLoot implementation from interface and the logic is still same as before.

At this moment there are no plans to remove systems of procedural content generation, but they shouldn't cause major issues. If other mods call getDrops method to get block loot - it will work fine. If they use direct loot tables instead - they will just get empty table

**Comment by lukebemish** [comment]
Yes, this all makes sense - this is why I had recommended either using the new datagen system, or ARRP, either of which would let you avoid manually making large numbers of JSON files, while still allowing other mods to access loot tables in an expected way.

**Comment by paulevsGitch** [comment]
Probably good solution will be switch direct mixins to Fabric loot table API. Blocks will still use an interface and automatically generate tables, but all loot will be available in resource manager as loot tables. I will put this into roadmap plan
