### ISSUE TITLE
Crash with no-vanilla generator worlds

### ISSUE THREAD

**Issue by Gamerbolts** [paulevsGitch/BCLib#85]
Hello! I am creating a modpack and seem to have a crash when I load the world. Here is the crashlog. It is between BClib and AE2 so I will be posting to both of you. :) https://bytebin.lucko.me/zSiM1HvCJf Any help is appreciated ty!

**Comment by quiqueck** [comment]
Thanks for reporting. Could you please also post the complete logs.

**Comment by Gamerbolts** [comment]
[latest.log](https://github.com/paulevsGitch/BCLib/files/8004619/latest.log)

**Comment by quiqueck** [comment]
1.3.1 will have a fix. However, you are using TerraBlender which is currently not compatible with BCLib (or Better Nether).

Basically no BetterNether Biomes will be generated in a new world. You'll have to close the game after creating a world and restart it, and let the our AutoFixer run in order to get our Biomes, but that will in turn disable all Nether-Biomes that are added through TerraBlender.  

Please see paulevsGitch/BetterNether#504 for more information.

**Comment by Gamerbolts** [comment]
I did not know this. Ok I will remove TerraBlender. Thank you!

**Comment by quiqueck** [comment]
1.3.1 was just released and should fix this crash. Please re-open this issue if you still have the same problem after upgrading.
